version: '3'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
  
  streamlit:
    build: .
    command: streamlit run src/app.py
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped